### ISSUE TITLE
create a package on npm

### ISSUE THREAD

**Issue by spruce** [markdicksonjr/node-mongo-backup-manager#1]
hey,
why haven't you pushed this repo to npm?
Would be nice to be able to install it from there and not use git directly. (I think it is bad practice because you never now what you get)

**Comment by spruce** [comment]
Ping?
@markdicksonjr

**Comment by markdicksonjr** [comment]
You're right! I'll try to get on that in the next few days :)

**Comment by spruce** [comment]
Would love to help also maintain this module. On github and npm if you have not much time to maintain it as I'm using it for more or less serious projects where I would like it to be maintained.

**Comment by markdicksonjr** [comment]
Awesome. That would be great!

**Comment by spruce** [comment]
Could you create the npm package under your name and maybe give me rights to publish? @markdicksonjr

**Comment by spruce** [comment]
Thanks for creating the package on npm
